# @format

version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
      - image: circleci/node:10-browsers ## makes virtual environment
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - run:
          name: run tests and generate coverage
          command: npm run cov
      - codecov/upload:
          file: "./coverage/clover.xml"
          token: b2dee972-978d-4f36-a032-e5dbe30340c1
      - run:
          name: Build
          command: CI=false npm run build
      # - run:
      #       name: Firebase Deploy
workflows:
  build:
    jobs:
      - "build"
      - cypress/run
